name: Trigger Main Repo Update

on:
  push:
    branches:
      - master

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Send repository_dispatch to main repo
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.MAIN_REPO_PAT }}" \
            https://api.github.com/repos/Jefino9488/TruthGuard_Frontend/dispatches \
            -d '{"event_type":"update-submodule"}'
